### ISSUE TITLE
Please include the package.json file

### ISSUE THREAD

**Issue by faluhub** [smocer/osurobot#3]
Please include the package.json file (not package-lock.json), so some other people can actually contribute :) thankuuuu also love this

**Comment by smocer** [comment]
Hi, can you please tell me more about it? I'm new to JS development. Also, why isn't it possible to just clone the repo, make changes on your branch and create a pull request?

**Comment by faluhub** [comment]
I could clone the repo, but I couldn't install all the packages you're using. By including the package.json file I only need to run 1 single command to install everything you're using :)

**Comment by smocer** [comment]
but im not using any packages. Everything that is used comes out of box on my physical board. I'd even say that in future I plan to rewrite everything in C, so all the code required to run this will be in the repo

**Comment by faluhub** [comment]
So you've not run "npm install <package>" while creating this project ever?

**Comment by smocer** [comment]
Nope, i've just added the files and that's all

**Comment by smocer** [comment]
@wurgo if it's okay, i'll close the issue
